##A makefile for FlashPhoto and Mia

LIB_DIR = ./libphoto
FLASH_DIR = ./FlashPhoto
MIA_DIR = ./Mia

 all:
	cd $(LIB_DIR); make all
	cd $(FLASH_DIR); make all
	cd $(MIA_DIR); make all
 
 clean:
	cd $(LIB_DIR); make clean
	cd $(FLASH_DIR); make clean
	cd $(MIA_DIR); make clean
 
 cleanall: 
	cd $(LIB_DIR); make clean
	cd $(FLASH_DIR); make cleanall
	cd $(MIA_DIR); make clean